services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: ["run", "--enable-api", "--cors", "*", "--debug"]

  action-server:
    build:
      context: ./actions
      dockerfile: Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: ["start", "--actions", "actions"]

